# Generated by Django 3.2 on 2021-04-10 10:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nazwa')),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nazwa')),
                ('analysis_category', models.CharField(choices=[('TACTICAL', 'TAKTYCZNE'), ('TECHNICAL', 'TECHNICZNE'), ('MOTORICAL', 'MOTORYCZNE'), ('MENTAL', 'MENTALNE'), ('SOMATICAL', 'SOMATYCZNE')], max_length=15, null=True, verbose_name='kategoria')),
                ('analysis_subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factors', to='swot.analysissubcategory', verbose_name='podkategoria')),
            ],
        ),
        migrations.CreateModel(
            name='SwotAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Ostatnio zmienione')),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swot', to='user.player', verbose_name='Autor')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swot_category', models.CharField(choices=[('WEAKNESS', 'S?ABE STRONY'), ('UNKNOWN', 'NIEPRZYPISANE'), ('STRENGTH', 'MOCNE STRONY')], default='UNKNOWN', max_length=15, verbose_name='klasyfikacja')),
                ('factor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_factors', to='swot.factor', verbose_name='czynnik')),
                ('swot_analysis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_factors', to='swot.swotanalysis', verbose_name='Analiza SWOT')),
            ],
        ),
    ]
