# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_remove_player_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=250, verbose_name='Nazwa')),
            ],
        ),
        migrations.CreateModel(
            name='SwotAnalyzis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Ostatnio zmienione')),
                ('factor', models.ManyToManyField(related_name='belongs_to_analyze', to='swot.Factor', verbose_name='Czynnik')),
                ('owner', models.ManyToManyField(related_name='swot', to='user.Player', verbose_name='Autor')),
            ],
        ),
    ]
