# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='analysis_category',
            field=models.CharField(choices=[('TACTICAL', 'TAKTYCZNE'), ('TECHNICAL', 'TECHNICZNE'), ('MOTORICAL', 'MOTORYCZNE'), ('MENTAL', 'MENTALNE'), ('SOMATICAL', 'SOMATYCZNE')], max_length=15, null=True, verbose_name='kategoria'),
        ),
        migrations.AddField(
            model_name='factor',
            name='swot_category',
            field=models.CharField(choices=[('WEAKNESS', 'S?ABE STRONY'), ('STRENGTH', 'MOCNE STRONY'), ('UNKNOWN', 'NIEPRZYPISANE')], default='UNKNOWN', max_length=15, verbose_name='klasyfikacja'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='name',
            field=models.TextField(max_length=250, verbose_name='nazwa'),
        ),
    ]
