# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20171231_1245'),
        ('swot', '0002_auto_20180102_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swot_category', models.CharField(choices=[('UNKNOWN', 'NIEPRZYPISANE'), ('STRENGTH', 'MOCNE STRONY'), ('WEAKNESS', 'S?ABE STRONY')], default='UNKNOWN', max_length=15, verbose_name='klasyfikacja')),
            ],
        ),
        migrations.RemoveField(
            model_name='factor',
            name='swot_category',
        ),
        migrations.RemoveField(
            model_name='swotanalyzis',
            name='factor',
        ),
        migrations.AlterField(
            model_name='factor',
            name='name',
            field=models.CharField(max_length=250, verbose_name='nazwa'),
        ),
        migrations.RemoveField(
            model_name='swotanalyzis',
            name='owner',
        ),
        migrations.AddField(
            model_name='swotanalyzis',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swot', to='user.Player', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='swotanalyzis',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Ostatnio zmienione'),
        ),
        migrations.AddField(
            model_name='playerfactor',
            name='factor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_factor', to='swot.Factor', verbose_name='czynnik'),
        ),
        migrations.AddField(
            model_name='playerfactor',
            name='swot_analysis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_factors', to='swot.SwotAnalyzis', verbose_name='Analiza SWOT'),
        ),
    ]
