# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0003_auto_20180102_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nazwa')),
            ],
        ),
        migrations.AlterField(
            model_name='playerfactor',
            name='factor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_factors', to='swot.Factor', verbose_name='czynnik'),
        ),
        migrations.AlterField(
            model_name='playerfactor',
            name='swot_category',
            field=models.CharField(choices=[('UNKNOWN', 'NIEPRZYPISANE'), ('WEAKNESS', 'S?ABE STRONY'), ('STRENGTH', 'MOCNE STRONY')], default='UNKNOWN', max_length=15, verbose_name='klasyfikacja'),
        ),
        migrations.AddField(
            model_name='factor',
            name='analysis_subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factors', to='swot.AnalysisSubCategory', verbose_name='podkategoria'),
        ),
    ]
