# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-10 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0005_auto_20180102_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerfactor',
            name='swot_category',
            field=models.CharField(choices=[('WEAKNESS', 'S?ABE STRONY'), ('UNKNOWN', 'NIEPRZYPISANE'), ('STRENGTH', 'MOCNE STRONY')], default='UNKNOWN', max_length=15, verbose_name='klasyfikacja'),
        ),
    ]
