# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-10 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0006_auto_20210410_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerfactor',
            name='swot_category',
            field=models.CharField(choices=[('UNKNOWN', 'NIEPRZYPISANE'), ('STRENGTH', 'MOCNE STRONY'), ('WEAKNESS', 'S?ABE STRONY')], default='UNKNOWN', max_length=15, verbose_name='klasyfikacja'),
        ),
    ]
