# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-23 01:03
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('address', models.CharField(blank=True, default='', max_length=100, verbose_name='Adres')),
                ('homepage', models.URLField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('age_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kategoria_wiekowa', to='trainings.AgeCategory', verbose_name='kategoria wiekowa')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='klub', to='team.Club', verbose_name='Klub')),
            ],
        ),
    ]
