# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-23 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='coaches',
            field=models.ManyToManyField(blank=True, related_name='teams', to='user.Coach', verbose_name='trenerzy'),
        ),
    ]
