# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-23 16:26
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_player_team'),
        ('team', '0003_remove_team_age_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(null=True, related_name='teams', to='user.Player', verbose_name='druzyna'),
        ),
        migrations.AlterField(
            model_name='team',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='team.Club', verbose_name='Klub'),
        ),
    ]
