# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-24 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20171223_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(related_name='teams', to='user.Player', verbose_name='Zawodnicy'),
        ),
    ]
