# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-23 00:43
from __future__ import unicode_literals

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='kategoria')),
            ],
            options={
                'verbose_name': 'Kategoria wiekowa',
                'verbose_name_plural': 'Kategoria wiekowa',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250, verbose_name='Tytuł')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Data i godzina')),
                ('duration', models.IntegerField(blank=True, default='90', verbose_name='czas trwania')),
                ('place', models.TextField(blank=True, verbose_name='miejsce')),
                ('type', models.CharField(choices=[('training', 'Training'), ('match', 'Match'), ('meeting', 'Meeting')], default='training', max_length=10, verbose_name='typ')),
                ('content', models.TextField(blank=True, default='', verbose_name='treść')),
                ('summary', models.TextField(blank=True, default='', verbose_name='podsumowanie')),
                ('author', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_events', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('techniqe', 'Technika'), ('tactics', 'Taktyka'), ('motorics', 'Motoryka'), ('other', 'Inna')], default='other', max_length=20, verbose_name='kategoria')),
                ('title', models.CharField(blank=True, default='', max_length=250, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, default='', verbose_name='opis')),
                ('duration', models.IntegerField(blank=True, default='', verbose_name='czas trwania')),
                ('age_category', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='trainings.AgeCategory')),
                ('author', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autor', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
            ],
            managers=[
                ('techniqe', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='exercises',
            field=models.ManyToManyField(to='trainings.Exercise'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, default='', related_name='participate_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='performer',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perform_events', to=settings.AUTH_USER_MODEL, verbose_name='wykonujący'),
        ),
        migrations.AddField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='trainings.Event'),
        ),
    ]
