# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-23 15:43
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_coaches'),
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='team',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='team.Team', verbose_name='treningi'),
        ),
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings_created', to='user.Coach', verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, default='', related_name='trainings', to='user.Player'),
        ),
        migrations.AlterField(
            model_name='event',
            name='performer',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings_performed', to='user.Coach', verbose_name='wykonujący'),
        ),
    ]
