# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-23 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_auto_20171223_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='exercises',
        ),
    ]
