# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_auto_20171122_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='age_category',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='trainings.TrainingAge'),
        ),
        migrations.AlterField(
            model_name='trainingage',
            name='name',
            field=models.CharField(max_length=20, verbose_name='kategoria'),
        ),
    ]
