# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_auto_20171122_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingage',
            options={'verbose_name': 'Kategoria wiekowa', 'verbose_name_plural': 'Kategoria wiekowa'},
        ),
    ]
