# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-24 20:53
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_remove_event_exercises'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.IntegerField(blank=True, default='90', verbose_name='Czas trwania'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, default='', related_name='trainings', to='user.Player', verbose_name='Uczestnicy'),
        ),
        migrations.AlterField(
            model_name='event',
            name='performer',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings_performed', to='user.Coach', verbose_name='Wykonawca'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.TextField(blank=True, verbose_name='Miejsce'),
        ),
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=models.TextField(blank=True, default='', verbose_name='Podsumowanie'),
        ),
        migrations.AlterField(
            model_name='event',
            name='team',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='team.Team', verbose_name='Zespół'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('training', 'Trening'), ('match', 'Mecz'), ('meeting', 'Spotkanie')], default='training', max_length=10, verbose_name='Typ'),
        ),
    ]
