# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_auto_20171122_1342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainingAge',
            new_name='AgeCategory',
        ),
    ]
