# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20171231_1245'),
        ('trainings', '0004_auto_20171224_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='performer',
        ),
        migrations.AddField(
            model_name='event',
            name='performer',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='trainings_performed', to='user.Coach', verbose_name='Wykonawca'),
        ),
    ]
