# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 21:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_auto_20171210_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_events', to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, default='', to=settings.AUTH_USER_MODEL, verbose_name='participate_events'),
        ),
        migrations.AlterField(
            model_name='event',
            name='performer',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perform_events', to=settings.AUTH_USER_MODEL, verbose_name='wykonujący'),
        ),
    ]
