# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 21:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_auto_20171211_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, default='', related_name='participate_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
