# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faf', '0001_initial'),
        ('user', '0003_remove_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='motorics_factors',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to', to='faf.MotoricsFactors', verbose_name='Motoryka'),
        ),
    ]
