# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faf', '0007_motoricsfactors_date'),
        ('user', '0004_player_motorics_factors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='motorics_factors',
        ),
        migrations.AddField(
            model_name='player',
            name='motorics_factors',
            field=models.ManyToManyField(blank=True, default='', related_name='player', to='faf.MotoricsFactors', verbose_name='Motoryka'),
        ),
    ]
