# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faf', '0007_motoricsfactors_date'),
        ('user', '0005_auto_20171231_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='somatics_factors',
            field=models.ManyToManyField(blank=True, default='', related_name='player', to='faf.SomaticsFactors', verbose_name='Somatyka'),
        ),
    ]
