# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotoricsFactors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.CharField(max_length=300, verbose_name='Si?a')),
                ('endurance', models.CharField(max_length=300, verbose_name='Wytrzyma?o??')),
                ('velocity', models.CharField(max_length=300, verbose_name='Szybko??')),
                ('coordination', models.CharField(max_length=300, verbose_name='Koordynacja')),
            ],
        ),
        migrations.CreateModel(
            name='SomaticFactors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('bmi', models.IntegerField()),
                ('fat', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='motoricsfactors',
            name='somatics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faf.SomaticFactors'),
        ),
    ]
