# Generated by Django 3.2 on 2021-04-10 10:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomaticsFactors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Data')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('bmi', models.FloatField()),
                ('fat', models.FloatField()),
                ('player', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='somatics_factors', to='user.player', verbose_name='owner')),
            ],
        ),
        migrations.CreateModel(
            name='MotoricsFactors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Data')),
                ('strength', models.CharField(max_length=300, verbose_name='Si?a')),
                ('endurance', models.CharField(max_length=300, verbose_name='Wytrzyma?o??')),
                ('velocity', models.CharField(max_length=300, verbose_name='Szybko??')),
                ('coordination', models.CharField(max_length=300, verbose_name='Koordynacja')),
                ('player', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motorics_factors', to='user.player', verbose_name='owner')),
            ],
        ),
    ]
