# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motoricsfactors',
            name='somatics',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motorics', to='faf.SomaticFactors', verbose_name='Parametry Somatyczne'),
        ),
    ]
