# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faf', '0002_auto_20171231_0324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SomaticFactors',
            new_name='SomaticsFactors',
        ),
    ]
