# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faf', '0003_auto_20171231_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='somaticsfactors',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Data'),
        ),
    ]
