# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faf', '0004_somaticsfactors_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='somaticsfactors',
            name='bmi',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='somaticsfactors',
            name='fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='somaticsfactors',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='somaticsfactors',
            name='weight',
            field=models.FloatField(),
        ),
    ]
