# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faf', '0006_remove_motoricsfactors_somatics'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoricsfactors',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Data'),
        ),
    ]
