# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faf', '0008_auto_20171231_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motoricsfactors',
            name='player',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motorics_factors', to='user.Player', verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='somaticsfactors',
            name='player',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='somatics_factors', to='user.Player', verbose_name='owner'),
        ),
    ]
